openapi: 3.0.0
info: 
  title: File Uploader
  description: File uploading web service
  version: 1.0.1

servers: 
  - url: http://localhost:500
    description: localhost version of our application

components:
  securitySchemes:
    cookieAuth:         
      type: apiKey
      in: cookie
      name: token
 